version: '3'
services:
    application:
        build: ./etc/application
        expose:
            - "8000"
        restart: always
        volumes:
            - ./etc/application/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ${APP_PATH}:/var/www/html
        command: "php bin/monotype server:run"
