monotype_repository:
    resource: "@RepositoryBundle/Controller/"
    type:     annotation
    prefix:   /

monotype_transport_layer:
    resource: "@MonotypeTransportLayerBundle/Controller/"
    type:     annotation
    prefix:   /

