monotype_bowman_stocks:
    resource: "@MonotypeBowmanBundle/Controller/StocksController.php"
    type:     annotation

monotype_bowman_machines:
    resource: "@MonotypeBowmanBundle/Controller/MachinesController.php"
    type:     annotation

monotype_bowman_process:
    resource: "@MonotypeBowmanBundle/Controller/ProcessController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
