_processor:
    resource: "@ProcessingBundle/Resources/config/routes.yml"
    prefix: /_processing

monotype_bowman_process:
    resource: "@MonotypeBowmanBundle/Controller/ProcessController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
