monotype_pos_users:
    resource: "@MonotypePosBundle/Controller/UsersController.php"
    type:     annotation

monotype_bowman_stocks:
    resource: "@MonotypeDirectControllBundle/Controller/StocksController.php"
    type:     annotation

monotype_bowman_machines:
    resource: "@MonotypeDirectControllBundle/Controller/MachinesController.php"
    type:     annotation

monotype_bowman_process:
    resource: "@MonotypeDirectControllBundle/Controller/ProcessController.php"
    type:     annotation

monotype_bowman_synchro:
    resource: "@MonotypeDirectControllBundle/Controller/SynchroController.php"
    type:     annotation

monotype_pos:
    resource: "@MonotypePosBundle/Controller/"
    type:     annotation
    prefix:   /
