monotype_directcontroll_stocks:
    resource: "@MonotypeDirectControllBundle/Controller/StocksController.php"
    type:     annotation

monotype_directcontroll_machines:
    resource: "@MonotypeDirectControllBundle/Controller/MachinesController.php"
    type:     annotation

monotype_directcontroll_process:
    resource: "@MonotypeDirectControllBundle/Controller/ProcessController.php"
    type:     annotation

monotype_directcontroll_synchro:
    resource: "@MonotypeDirectControllBundle/Controller/SynchroController.php"
    type:     annotation

monotype_pos:
    resource: "@MonotypePosBundle/Controller/"
    type:     annotation
