monotype_manager_customer:
    resource: "@MonotypeManagerBundle/Controller/CustomerController.php"
    type:     annotation

monotype_bowman_stocks:
    resource: "@MonotypeDirectControllBundle/Controller/StocksController.php"
    type:     annotation

monotype_bowman_machines:
    resource: "@MonotypeDirectControllBundle/Controller/MachinesController.php"
    type:     annotation

monotype_bowman_process:
    resource: "@MonotypeDirectControllBundle/Controller/ProcessController.php"
    type:     annotation

monotype_bowman_synchro:
    resource: "@MonotypeDirectControllBundle/Controller/SynchroController.php"
    type:     annotation

monotype_pos:
    resource: "@MonotypePosBundle/Controller/"
    type:     annotation
    prefix:   /

monotype_utility:
    resource: "@MonotypeUtilityBundle/Controller/"
    type:     annotation
    prefix:
monotype_manager_bundle:
    resource: "@MonotypeManagerBundle/Controller/"
    type:     annotation
    prefix:   /

#user_registration:
#    path:     /register
#    defaults: { _controller: Monotype\Bundle\AppBundle:Registration:register }

logout:
   path: /logout
