monotype_bowman_stocks:
    resource: "@MonotypeBowmanBundle/Controller/StocksController.php"
    type:     annotation

monotype_bowman_machines:
    resource: "@MonotypeBowmanBundle/Controller/MachinesController.php"
    type:     annotation

monotype_bowman_process:
    resource: "@MonotypeBowmanBundle/Controller/ProcessController.php"
    type:     annotation

monotype_bowman_synchro:
    resource: "@MonotypeBowmanBundle/Controller/SynchroController.php"
    type:     annotation

monotype_pos:
    resource: "@MonotypePosBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
