<?php

namespace Monotype\Bundle\ManagerBundle\Repository;

/**
 * WorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
