<?php

namespace Monotype\Bundle\DirectControllBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksRepository extends EntityRepository
{
}
